import { GetServerSideProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Tenant } from "../../@types/Tenant";
import { Button } from "../../components/Button";
import { Divider } from "../../components/Divider";
import { Header } from "../../components/Header";
import { InputField } from "../../components/InputField";
import { useAppContext } from "../../context/app";
import { _useApi } from "../../libs/hooks/useApi";
import styles from "../../styles/Forget.module.css";

type PropsTenant = {
  tenantInfo: Tenant;
};

function Forget({ tenantInfo }: PropsTenant) {
  const { tenant, setTenant } = useAppContext();
  const router = useRouter();
  const [inputEmail, setInputEmail] = useState("");


  useEffect(() => {
    if (tenant != tenantInfo) {
      setTenant(tenantInfo);
    }
  }, [setTenant, tenant, tenantInfo]);

  return (
    tenant && (
      <div className={styles.container}>
        <Head>
          <title>Esqueci a senha | {tenant?.slug} </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header href={`/${tenant?.slug}/login`} />

        <div className={styles.title}>{tenant.name}</div>

        <div className={styles.title2}>Esqueceu sua senha?</div>

        <div className={styles.subTitleContainer}>
          <p className={styles.subTitle}>
            Preencha o campo com seu e-mail <br /> e receba as instruções
            necessárias
            <br />
            para redefinir a sua senha
          </p>
        </div>

        <Divider size="300px" />

        <div style={{ marginTop: "30px" }}>
          <InputField
            onChange={(e) => setInputEmail(e.target.value)}
            value={inputEmail}
            placeholder="Digite seu Email"
          />
        </div>

        <Button
          label="Enviar"
          onClick={() => {
            router.push(`/${tenant.slug}/forget-success`);
          }}
        />
      </div>
    )
  );
}

export default Forget;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { tenant: tenantSlug } = ctx.query;
  const api = _useApi(tenantSlug as string);

  const tenantInfo = await api.getTenant();

  if (!tenantInfo) {
    return { redirect: { destination: "/", permanent: false } };
  }

  return {
    props: {
      tenantInfo,
    },
  };
};
