import { GetServerSideProps } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { Tenant } from "../../@types/Tenant";
import { Banner } from "../../components/banner";
import { ProductItem } from "../../components/ProductItem";
import { SearchInput } from "../../components/SearchInput";
import { useAppContext } from "../../context/AppContext";
import { _useApi } from "../../libs/hooks/useApi";
import styles from "../../styles/Home.module.css";

type PropsTenant = {
  tenantInfo: Tenant;
};

function Home({ tenantInfo }: PropsTenant) {
  const { tenant, setTenant } = useAppContext();

  useEffect(() => {
    setTenant(tenantInfo);
  }, [setTenant, tenantInfo]);

  const handleSearch = (handleSearch: string) => {
    console.log(`Você esta procurando por ${handleSearch}`);
  };

  return (
    tenant && (
      <div className={styles.container}>
        <Head>
          <title>Pagina Inicial</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className={styles.header}>
          <div className={styles.headerTop}>
            <div className={styles.headerTopLeft}>
              <div className={styles.headerTitle}>Seja Bem Vindo (a) 👋 </div>
              <div className={styles.headerSubTitle}>
                O que deseja para hoje?
              </div>
            </div>
            <div className={styles.headerTopRight}>
              <div className={styles.menuButton}>
                <div
                  className={styles.menuButtonLine}
                  style={{
                    background:
                      tenant?.mainColor,
                  }}
                ></div>
                <div
                  className={styles.menuButtonLine}
                  style={{
                    background:
                      tenant?.mainColor,
                  }}
                ></div>
                <div
                  className={styles.menuButtonLine}
                  style={{
                    background:
                      tenant?.mainColor,
                  }}
                ></div>
              </div>
            </div>
          </div>
          <div className={styles.headerBottom}>
            <SearchInput
              onSearch={handleSearch}
            />
          </div>
        </header>
        <main>
          <Banner />

          <div className={styles.grid}>
            <ProductItem
              data={{
                id: 1,
                name: "Texas Burger",
                categoryName: "Tradicional",
                image: "/tmp/burguer-01.png",
                price: "R$29,50",
              }}
            />

            <ProductItem
              data={{
                id: 1,
                name: "Texas Burger",
                categoryName: "Tradicional",
                image: "/tmp/burguer-01.png",
                price: "R$29,50",
              }}
            />

            <ProductItem
              data={{
                id: 1,
                name: "Texas Burger",
                categoryName: "Tradicional",
                image: "/tmp/burguer-01.png",
                price: "R$29,50",
              }}
            />

            <ProductItem
              data={{
                id: 1,
                name: "Texas Burger",
                categoryName: "Tradicional",
                image: "/tmp/burguer-01.png",
                price: "R$29,50",
              }}
            />

            <ProductItem
              data={{
                id: 1,
                name: "Texas Burger",
                categoryName: "Tradicional",
                image: "/tmp/burguer-01.png",
                price: "R$29,50",
              }}
            />
          </div>
        </main>
      </div>
    )
  );
}

export default Home;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { tenant: tenantSlug } = ctx.query;
  const api = _useApi();

  const tenantInfo = await api.getTenant(tenantSlug as string);

  if (!tenantInfo) {
    return { redirect: { destination: "/", permanent: false } };
  }

  return {
    props: {
      tenantInfo,
    },
  };
};
