import { GetServerSideProps } from "next";
import Head from "next/head";
import { useState } from "react";
import { Banner } from "../../components/banner";
import { ProductItem } from "../../components/ProductItem";
import { SearchInput } from "../../components/SearchInput";
import { getTenantResponse, _useApi } from "../../libs/hooks/useApi";
import styles from "../../styles/Home.module.css";

type PropsTenant = {
  tenant:getTenantResponse
}

function Home({tenant}:PropsTenant) {
  const [mainColorApp, setMainColorApp] = useState(tenant.mainColor); //"#FB9400"
  const [secundaryColorApp, setSecundaryColorApp] = useState(tenant.secundColor); //"#FFF9F2"

  const handleSearch = (handleSearch: string) => {
    console.log(`Você esta procurando por ${handleSearch}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Pagina Inicial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.headerTop}>
          <div className={styles.headerTopLeft}>
            <div className={styles.headerTitle}>Seja Bem Vindo (a) 👋 </div>
            <div className={styles.headerSubTitle}>O que deseja para hoje?</div>
          </div>
          <div className={styles.headerTopRight}>
            <div className={styles.menuButton}>
              <div
                className={styles.menuButtonLine}
                style={{
                  background: mainColorApp || "var(--primary-color-default)",
                }}
              ></div>
              <div
                className={styles.menuButtonLine}
                style={{
                  background: mainColorApp || "var(--primary-color-default)",
                }}
              ></div>
              <div
                className={styles.menuButtonLine}
                style={{
                  background: mainColorApp || "var(--primary-color-default)",
                }}
              ></div>
            </div>
          </div>
        </div>
        <div className={styles.headerBottom}>
          <SearchInput mainColor={mainColorApp} onSearch={handleSearch} />
        </div>
      </header>
      <main>
        <Banner />

        <div className={styles.grid}>
          <ProductItem
            data={{
              id: 1,
              name: "Texas Burger",
              categoryName: "Tradicional",
              image: "/tmp/burguer-01.png",
              price: "R$29,50",
            }}
            primaryColor={mainColorApp}
            secundaryColor={secundaryColorApp}
          />

          <ProductItem
            data={{
              id: 1,
              name: "Texas Burger",
              categoryName: "Tradicional",
              image: "/tmp/burguer-01.png",
              price: "R$29,50",
            }}
            primaryColor={mainColorApp}
            secundaryColor={secundaryColorApp}
          />

          <ProductItem
            data={{
              id: 1,
              name: "Texas Burger",
              categoryName: "Tradicional",
              image: "/tmp/burguer-01.png",
              price: "R$29,50",
            }}
            primaryColor={mainColorApp}
            secundaryColor={secundaryColorApp}
          />

          <ProductItem
            data={{
              id: 1,
              name: "Texas Burger",
              categoryName: "Tradicional",
              image: "/tmp/burguer-01.png",
              price: "R$29,50",
            }}
            primaryColor={mainColorApp}
            secundaryColor={secundaryColorApp}
          />

          <ProductItem
            data={{
              id: 1,
              name: "Texas Burger",
              categoryName: "Tradicional",
              image: "/tmp/burguer-01.png",
              price: "R$29,50",
            }}
            primaryColor={mainColorApp}
            secundaryColor={secundaryColorApp}
          />
        </div>
      </main>
    </div>
  );
}

export default Home;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { tenant: tenantSlug } = ctx.query;
  const api = _useApi();

  const tenant = await api.getTenant(tenantSlug as string);

  if (!tenant) {
    return { redirect: { destination: "/", permanent: false } };
  }

  return {
    props: {
      tenant,
    },
  };
};
