import { GetServerSideProps } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Tenant } from "../../@types/Tenant";
import { Button } from "../../components/Button";
import { Divider } from "../../components/Divider";
import { Header } from "../../components/Header";
import { InputField } from "../../components/InputField";
import { useAppContext } from "../../context/app";
import { _useApi } from "../../libs/hooks/useApi";
import styles from "../../styles/Login.module.css";

type PropsTenant = {
  tenantInfo: Tenant;
};

function Login({ tenantInfo }: PropsTenant) {
  const { tenant, setTenant } = useAppContext();
  const router = useRouter();
  const [inputEmail, setInputEmail] = useState("");
  const [inputPassword, setInputPassword] = useState("");
  const [hasEye, setHasEye] = useState(true);

  useEffect(() => {
    if (tenant != tenantInfo) {
      setTenant(tenantInfo);
    }
  }, [setTenant, tenant, tenantInfo]);

  return (
    tenant && (
      <div className={styles.container}>
        <Head>
          <title>Login | {tenant?.slug} </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header href={`/${tenant?.slug}`} />

        <div className={styles.title}>{tenant.name}</div>

        <div className={styles.subTitleContainer}>
          <p className={styles.subTitle}>
            Use suas credenciais <br />
            para realizar o login.
          </p>
        </div>

        <Divider size="213px" />

        <div>
          <InputField
            onChange={(e) => setInputEmail(e.target.value)}
            value={inputEmail}
            placeholder="Digite seu Email"
          />
          <InputField
            onChange={(e) => setInputPassword(e.target.value)}
            typeInp="password"
            value={inputPassword}
            placeholder="Digite sua Senha"
            eyeStatus={hasEye}
            onEye={() => setHasEye(!hasEye)}
          />
        </div>

        <Button label="Entrar" onClick={() => {}} />

        <div className={styles.forget}>
          <p>Esqueceu sua senha?</p>
          <Link
            href={`/${tenant.slug}/forget`}
            style={{ color: tenant.mainColor }}
          >
            Clique aqui
          </Link>
        </div>

        <Divider size="255px" />

        <Button
          label="Quero me cadastrar"
          onClick={() => {
            router.push(`/${tenant.slug}/signup`);
          }}
          outline
          top="62px"
        />
      </div>
    )
  );
}

export default Login;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { tenant: tenantSlug } = ctx.query;
  const api = _useApi(tenantSlug as string);

  const tenantInfo = await api.getTenant();

  if (!tenantInfo) {
    return { redirect: { destination: "/", permanent: false } };
  }

  return {
    props: {
      tenantInfo,
    },
  };
};
