import { GetServerSideProps } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Tenant } from "../../@types/Tenant";
import { Button } from "../../components/Button";
import { Divider } from "../../components/Divider";
import { Header } from "../../components/Header";
import { InputField } from "../../components/InputField";
import { useAppContext } from "../../context/app";
import { _useApi } from "../../libs/hooks/useApi";
import styles from "../../styles/SignUp.module.css";

type PropsTenant = {
  tenantInfo: Tenant;
};

function SignUp({ tenantInfo }: PropsTenant) {
  const { tenant, setTenant } = useAppContext();
  const [hasEye, setHasEye] = useState(true);
  const [inputName, setInputName] = useState("");
  const [inputEmail, setInputEmail] = useState("");
  const [inputPassword, setInputPassword] = useState("");
  const [inputPasswordConfirm, setInputPasswordConfirm] = useState("");

  useEffect(() => {
    if (tenant != tenantInfo) {
      setTenant(tenantInfo);
    }
  }, [setTenant, tenant, tenantInfo]);

  return (
    tenant && (
      <div className={styles.container}>
        <Head>
          <title>Cadastrar | {tenant?.slug} </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header href={`/${tenant?.slug}/login`} />

        <div className={styles.title}>{tenant.name}</div>

        <div className={styles.subTitleContainer}>
          <p className={styles.subTitle}>
            Preencha os campos <br />
            para criar o seu cadastro.
          </p>
        </div>

        <Divider size="223px" />

        <div>
          <InputField
            onChange={(e) => setInputName(e.target.value)}
            value={inputName}
            placeholder="Digite seu Nome"
          />
          <InputField
            onChange={(e) => setInputEmail(e.target.value)}
            value={inputEmail}
            placeholder="Digite seu Email"
          />
          <InputField
            onChange={(e) => setInputPassword(e.target.value)}
            typeInp="password"
            value={inputPassword}
            placeholder="Digite sua Senha"
            onEye={() => setHasEye(!hasEye)}
            eyeStatus={hasEye}
          />

          <InputField
            onChange={(e) => setInputPasswordConfirm(e.target.value)}
            typeInp="password"
            value={inputPasswordConfirm}
            placeholder="Confirme sua Senha"
            onEye={() => setHasEye(!hasEye)}
            eyeStatus={hasEye}
          />
        </div>

        <Button label="Cadastrar" onClick={() => {}} />

        <div className={styles.returnLogin}>
          <p>Já fez cadastro?</p>
          <Link
            href={`/${tenant.slug}/login`}
            style={{ color: tenant.mainColor }}
          >
            Fazer Login
          </Link>
        </div>
      </div>
    )
  );
}

export default SignUp;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { tenant: tenantSlug } = ctx.query;
  const api = _useApi(tenantSlug as string);

  const tenantInfo = await api.getTenant();

  if (!tenantInfo) {
    return { redirect: { destination: "/", permanent: false } };
  }

  return {
    props: {
      tenantInfo,
    },
  };
};
