import Head from "next/head";
import { useState } from "react";
import { SearchInput } from "../components/SearchInput";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [mainColorApp, setMainColorApp] = useState("#FB9400"); //"#FB9400"

  const handleSearch = (handleSearch: string) => {
    console.log(`Você esta procurando por ${handleSearch}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Pagina Inicial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.headerTop}>
          <div className={styles.headerTopLeft}>
            <div className={styles.headerTitle}>Seja Bem Vindo (a) 👋 </div>
            <div className={styles.headerSubTitle}>O que deseja para hoje?</div>
          </div>
          <div className={styles.headerTopRight}>
            <div className={styles.menuButton}>
              <div className={styles.menuButtonLine} style={{background: mainColorApp}}></div>
              <div className={styles.menuButtonLine} style={{background: mainColorApp}}></div>
              <div className={styles.menuButtonLine} style={{background: mainColorApp}}></div>
            </div>
          </div>
        </div>
        <div className={styles.headerBottom}>
          <SearchInput mainColor={mainColorApp} onSearch={handleSearch} />
        </div>
      </header>
      <main>
        <h1>Seja bem vindo(a)</h1>
      </main>
    </div>
  );
}
